name: 23f2003724@ds.study.iitm.ac.in

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print email
        run: echo "23f2003724@ds.study.iitm.ac.in"
